### PR TITLE
Add configurable logging

### LINKED ISSUE #39: configurable logging
I'd like logging to be configurable, similar to what you did with `synced-cron`. Thoughts?

### PR DESCRIPTION
**Pull request by meonkeys**
Most of this is copied and pasted from [synced-cron](https://github.com/percolatestudio/meteor-synced-cron) code.

Note that both this and #38 are branches off master, so one of these will merge cleanly and the other will need to be updated to merge cleanly.

Closes #39.

All tests pass, but there is an error in the console:

```
(STDERR) Trace: event after complete!
(STDERR)     at [object Object].wrappedOnEvent [as onEvent] (packages/tinytest/tinytest.js:394:1)
(STDERR)     at [object Object]._.extend.ok (packages/tinytest/tinytest.js:32:1)
(STDERR)     at [object Object]._.extend.isTrue (packages/tinytest/tinytest.js:250:1)
(STDERR)     at Migrations.options.logger (packages/local-test:percolate:migrations/migrations_tests.js:187:1)
(STDERR)     at Function.<anonymous> (packages/percolate:migrations/migrations_server.js:71:1)
(STDERR)     at Function.info (packages/underscore/underscore.js:646:1)
(STDERR)     at migrate (packages/percolate:migrations/migrations_server.js:199:1)
(STDERR)     at Object.Migrations._migrateTo (packages/percolate:migrations/migrations_server.js:213:1)
(STDERR)     at Object.Migrations.migrateTo (packages/percolate:migrations/migrations_server.js:141:1)
(STDERR)     at [object Object].Tinytest.addAsync.logger [as func] (packages/local-test:percolate:migrations/migrations_tests.js:192:1)
*** Test error -- test 'Migrations can log to injected logger' returned multiple times.
```

### CODE REVIEW

**Comment by meonkeys** [comment]
Ah, I figured out the test error. I just had to make sure the logging test assertions and `done()` only run once.

**Comment by meonkeys** [comment]
Fixed merge conflicts: rebased off master and force-pushed.

**Comment by zol** [comment]
Merged, thank you.

**Comment by zol** [comment]
We may have done this simultaneously. In any case, your changes were just released in version 0.9.6

**Comment by meonkeys** [comment]
Great! :apple:

**Pull request closed without merging**
